let source do the error handling

diff --git a/bin/ws-cmd b/bin/ws-cmd
--- a/bin/ws-cmd
+++ b/bin/ws-cmd
@@ -1,7 +1,14 @@
 #!/bin/bash
 
 S_LIB_FOLDER=${S_LIB_FOLDER:-/usr/lib/ws-session}
-source $S_LIB_FOLDER/core/source.sh
+if ! source $S_LIB_FOLDER/core/source.sh 2>/dev/null; then
+  echo "FATAL: cannot find core/source.sh, aborting!"
+  echo "       Install core files to /usr/lib/ws-cmd"
+  echo "       or export S_LIB_FOLDER,"
+  echo "       or temporary use: S_LIB_FOLDER=. ws-cmd"
+  exit 1
+fi
+
 s_source_lib wm
 
 if [[ -z "$@" ]] ; then
